# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >=  16 x 40G GPU
# running time ~32h
wandb_project: coder1
run_name: Qwen/Qwen2.5-7B-Instruct_lr_2.5e-7_bs_120_n_5

# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: dummy/dummy # This is not used; we preprocess the data before training
train_dataset_file: /export/home/data/coder1/code-r1-12k-leetcode2k-taco/train.parquet
test_dataset_file: /export/home/data/coder1/code-r1-12k-leetcode2k-taco/test.parquet

num_processes: 15

# Reward functions
reward_funcs: ["accuracy"]
# reward_weights: [1.0, 1.0]
# GRPO trainer config
use_vllm: true
output_dir: output/gsm8k
gradient_accumulation_steps: 4
max_prompt_length: 2048
num_generations: 3
max_completion_length: 2048

bf16: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.4
vllm_max_model_len: 4096
temperature: 1.0
do_eval: true
eval_strategy: "steps" # "no", "steps", "epoch"
eval_steps: 25

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.5e-06
beta: 0.001 # without KL
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 3
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 1
push_to_hub: False
report_to:
- wandb

save_strategy: "epoch"
resume_from_checkpoint: False
seed: 42
warmup_ratio: 0.1