# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >=  8 x 144G GPU
# running time ~32h

# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: xiaodongguaAIGC/X-R1-7500 # 750 / 1500 / 7500
dataset_configs:
- train
num_processes: 7

# GRPO trainer config
use_vllm: true
output_dir: output/X-R1-7B
gradient_accumulation_steps: 8
max_prompt_length: 256
num_generations: 14
max_completion_length: 1024

bf16: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
vllm_max_model_len: 2048
do_eval: false
eval_strategy: "no"
eval_steps: 10
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 3.0e-06
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 3
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
push_to_hub: False
report_to:
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1

# lora config
# task_type: model_args.lora_task_type
# lora_in_4bit: True # no support QLoRA
# lora_r: 128
# lora_target_modules: ["q_proj","v_proj", "k_proj", "embed_tokens"]
# lora_alpha: 8
# lora_dropout: 0.0
# bias: "none"
# use_peft: true